### ISSUE TITLE
Drills not working as intended 

### ISSUE THREAD

**Issue by Blacksail-1** [newbeauke/Droneboi#2]
This is in open world on single player and the 0.29.1 (beta) version. When I mine asteroids with the drill (I've got containers on the ship as well) the cargo bar does not fill up. So I went to the trade station afterward mining the asteroid and turns out I had no minerals at all to convert into scrap. I don't know if this is intended or is it a work in progress for the drill system.

**Comment by Nogardagem** [comment]
Did you happen to see a gold piece after mining some of the asteroid @Blacksail-1 ? If you didn't, then that's an intended feature. Some don't have minerals inside.

**Comment by newbeauke** [comment]
> Did you happen to see a gold piece after mining some of the asteroid @Blacksail-1 ? If you didn't, then that's an intended feature. Some don't have minerals inside.

Seems like that was indeed what happened
